### ISSUE TITLE
Get the Dart SDK - 获取 Dart SDK - [润稿]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dart.cn#14]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/get-dart.md

文档预览地址：http://www.dartdoc.cn/get-dart

建议完成天数：3 ~ 5 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by hayley1643** [comment]
感谢@AigeStudio 辛苦啦 翻译已经成功认领和登记

**Comment by AigeStudio** [comment]
这个已经翻译完合并了，我备注下，删分支了。
