### ISSUE TITLE
[Bug] 部署失败？

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dart.cn#158]
发现最新的修改并没有同步到 dartdoc 和 dart.cn，需要抽空检查一下。

- [x] CDN
- [x] CI 流程
- [x] 阿里云 OSS、ECS 规则

目前想不到其他的了。
@chenglu

**Comment by chenglu** [comment]
应该是 CI 脚本出错了。

**Comment by chenglu** [comment]
是 CI 脚本的问题，目前已经修复了。
