### ISSUE TITLE
Obsolete pub features - 已失效的 pub 命令和功能

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dart.cn#17]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/tools/pub/obsolete.md

文档预览地址：http://www.dartdoc.cn/tools/pub/obsolete

建议完成天数：1 ~ 2 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by hayley1643** [comment]
感谢@AigeStudio 辛苦啦 翻译已经成功认领和登记

**Comment by AigeStudio** [comment]
这个已经翻译完合并了，我备注下，删分支了。
