### ISSUE TITLE
'Dart 编程语言概览' page issue

### ISSUE THREAD

**Issue by jweboy** [cfug/dart.cn#175]
Page URL: https://dart.cn/samples/
Page source: https://github.com/cfug/dart.cn/tree/master/src/samples/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
在函数章节中有错别字 `胖剪头` ，应该是 `胖箭头`。

**Comment by chenglu** [comment]
这个问题已经在最新的 commits 里解决了，感谢提出，有任何问题再向我们提出，谢谢！
