### ISSUE TITLE
国内无法按照linux教程安装dart sdk

### ISSUE THREAD

**Issue by godot0413301** [cfug/dart.cn#196]
If you’re using Debian/Ubuntu on AMD64 (64-bit Intel), you can choose one of the following options, both of which can update the SDK automatically when new versions are released.

Install using apt-get
Install a Debian package
Install using apt-get
Perform the following one-time setup:
```
 sudo apt-get update
 sudo apt-get install apt-transport-https
 sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
 sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
```
以上的地址，在国内无法访问

**Comment by chenglu** [comment]
@godot0413301 

目前 Flutter 中国镜像并没有特别对 Dart SDK 做优化，先做下面的替换试试看？

```
 sudo apt-get update
 sudo apt-get install apt-transport-https
 sudo sh -c 'wget -qO- https://dl.google.com/linux/linux_signing_key.pub | apt-key add -'
 sudo sh -c 'wget -qO- https://storage.flutter-io.cn/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
```

有任何问题请在这个 issue 下跟进。

**Comment by chenglu** [comment]
`dl-ssl.google.com` 替换成 `dl.google.com`
`storage.googleapis.com` 替换成 `storage.flutter-io.cn`
