### ISSUE TITLE
'健全的空安全' page issue

### ISSUE THREAD

**Issue by Joshua-Chang** [cfug/dart.cn#220]
Page URL: https://dart.cn/null-safety/
Page source: https://github.com/cfug/dart.cn/tree/master/src/null-safety/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
in section Map types:
int value = <String, int>{'one': 1}['one']!; // OK
int? value = <String, int>{'one': 1}['one']; // OK
error:
This requires the 'non-nullable' language feature to be enabled,to set the minimum SDK constraint to 2.9 or higher
in sdk:2.9.1 still error

**Comment by chenglu** [comment]
Sorry about this, we have synced up with the official doc, please upgrade your Dart SDK version to the **most recent dev channel** to try the null-safety feature.
