### ISSUE TITLE
'Dart 开发语言概览' page issue

### ISSUE THREAD

**Issue by mingliao** [cfug/dart.cn#238]
Page URL: https://dart.cn/guides/language/language-tour
Page source: https://github.com/cfug/dart.cn/tree/master/src/_guides/language/language-tour.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
章节*类* 下的*使用构造函数*中，这句话 “但是如果无法根据上下文判断是否可以省略 cosnt，则不能省略掉 const 关键字“，

是否可以省略 **cosnt**  拼写错误

应纠正为**const**

**Comment by chenglu** [comment]
收到，会尽快修复，感谢提出这个问题！
