### ISSUE TITLE
'Dart 速查表 codelab' page issue

### ISSUE THREAD

**Issue by Bright0206** [cfug/dart.cn#267]
Page URL: https://dart.cn/codelabs/dart-cheatsheet/
Page source: https://github.com/cfug/dart.cn/tree/master/src/codelabs/dart-cheatsheet/index.md

![image](https://user-images.githubusercontent.com/33367187/110080975-33bdb780-7dc6-11eb-88dd-41171fdfd1ab.png)
这个可选位置参数上面写的是大括号，但是代码示例用的是中括号

**Comment by chenglu** [comment]
应该修改为「中括号」或者「方括号」。
