### ISSUE TITLE
Working with nullable types - 与可空类型共舞 中解释错误

### ISSUE THREAD

**Issue by lyzhonghua** [cfug/dart.cn#270]
空安全->深入理解空安全->与可空类型共舞

为了解决这类问题，我们从 C# 相同功能的设计中借鉴了一个聪明的处理方法。当您在链式方法调用中使用避空运算符时，如果接收器被判断为 null，那么整个链式调用的剩余部分都会被截断并跳过。这意味着如果 doohickey 的返回值是一个可空的类型，您应该这样写：

To address this, we borrowed a smart idea from C#’s design of the same feature. When you use a null-aware operator in a method chain, if the receiver evaluates to null, then the entire rest of the method chain is short-circuited and skipped. This means if doohickey has a non-nullable return type, then you can and should write:

最后一句的“这意味着如果 doohickey 的返回值是一个可空的类型”

但是英文对应的是“This means if doohickey has a non-nullable return type”

“non-nullable”是非空而不是“可空类型”吧

**Comment by AlexV525** [comment]
感谢订正，确实翻译有误，会尽快处理~
