### ISSUE TITLE
Catalog for mobile

### ISSUE THREAD

**Issue by Mister-Hope** [cfug/dart.cn#282]
![image](https://user-images.githubusercontent.com/33315834/114547573-2c28e280-9c91-11eb-9cae-5a7e287ff3d7.png)
![image](https://user-images.githubusercontent.com/33315834/114547605-36e37780-9c91-11eb-8450-e6024c08d49c.png)

Is it a bug?

**Comment by AlexV525** [comment]
dart.cn 的部分依赖还需要更新，目前已在等待跟进，感谢反馈。

**Comment by Mister-Hope** [comment]
应该不是依赖更新的问题，移动端和PC端的菜单应该不是同一个，PC端菜单可以正确的过滤掉英文标题，而移动端的菜单不会。

**Comment by AlexV525** [comment]
就是依赖问题呢...有时间会处理的

**Comment by AlexV525** [comment]
ref cfug/team#29

**Comment by chenglu** [comment]
这个 Issue 在这个 commit 里被解决：https://github.com/cfug/dart.cn/commit/d0516e9207e94e0b476c48057dd3122a633e7bdd
谢谢 @Mister-Hope 提出问题，谢谢 @AlexV525 跟进，也谢谢解决问题的 @asnowwolf
