### ISSUE TITLE
代码块中的英文是否不翻译?

### ISSUE THREAD

**Issue by iugo** [cfug/dart.cn#287]
一般来说, 文档是保留英文原文的, 但看到代码块这部分, 没有翻译, 也就没有中英文对比.

我们应该如何对此进行翻译?

1. 不翻译, 保留英文原文.
2. 直接翻译为中文, 不保留英文原文.
3. 在同一行增加中文翻译.
4. 新增新的代码块实现中文翻译. (前端是否支持?)

**Comment by chenglu** [comment]
谢谢 @iugo 的提醒和建议，我们之前尝试过 

```
// 英文注释 (英文注释的中文翻译)
```
和
```
// 英文注释
// 中文注释
```

等格式，因为中英双语工具并不会、也不应该处理这部分内容，因此过去并没有对代码注释进行过多的要求。

因为官方的 CI 的迭代，为了保证文档中代码的完整性和可运行性，CI 脚本开始检查文档里的代码和 GitHub repo 的一致性，因此我们建议未来代码中的注释采取 @iugo 提出的第一种方式进行，也就是保留英文原文，不作翻译。

谢谢！
