### ISSUE TITLE
'Asynchronous programming: futures, async, await' page issue

### ISSUE THREAD

**Issue by SoftJing1** [cfug/dart.cn#301]
Page URL: https://dart.cn/codelabs/async-await/
Page source: https://github.com/cfug/dart.cn/tree/master/src/codelabs/async-await/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
the function names in instruction don't match with those on the code pad. In instruction all function start with "get" should be changed to start with "fetch". for example "getUsername" should be modified into "fetchUsername" to keep consistency

**Comment by chenglu** [comment]
Hello @SoftJing1!

Thank you for raising this issue with us. We have deleted the old version of this codelab page, and it should work as expected now. Please do a Hard Refresh in your browser or revisit with the random URL parameters like https://dart.cn/codelabs/async-await?reload=1

Let us know if you have any further questions!
