### ISSUE TITLE
pub deps - pub deps 命令

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dart.cn#31]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/tools/pub/cmd/pub-deps.md

文档预览地址：http://www.dartdoc.cn/tools/pub/cmd/pub-deps

建议完成天数：1 ~ 2 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by AigeStudio** [comment]
这个已经翻译完合并了，我备注下，删分支了。
