### ISSUE TITLE
pub lish - pub lish 命令

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dart.cn#35]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/tools/pub/cmd/pub-lish.md

文档预览地址：http://www.dartdoc.cn/tools/pub/cmd/pub-lish

建议完成天数：1 ~ 2 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by hayley1643** [comment]
@AigeStudio 翻译的时候如果英文是斜体的话 对应的中文不是斜体哦，而是粗体 也就是前后加上**以及空格（翻译格式的一点小提醒）

**Comment by AigeStudio** [comment]
> @AigeStudio 翻译的时候如果英文是斜体的话 对应的中文不是斜体哦，而是粗体 也就是前后加上**以及空格（翻译格式的一点小提醒）

OK

**Comment by AigeStudio** [comment]
这个已经翻译完合并了，我备注下，删分支了。
