### ISSUE TITLE
[PAGE ISSUE]: '{Dart 开发语言概览}'

### ISSUE THREAD

**Issue by pcdeng** [cfug/dart.cn#353]
### 页面 URL

https://dart.cn/guides/language/language-tour#variables

### 描述问题

国内访问谷歌字体网站报错
![image](https://user-images.githubusercontent.com/5336505/149725415-502f7020-4d70-4dc1-b20a-2648926ccbf1.png)
所以页面显示错乱
![image](https://user-images.githubusercontent.com/5336505/149725500-76e53c98-f959-4c0a-abcc-fe43330ff083.png)

### 期望如何修复

替换字体或者其它方案，使页面显示正常。

**Comment by chenglu** [comment]
@pcdeng 你好，就目前的网络情况下，Fonts API 的 [服务器](https://ping.chinaz.com/fonts.googleapis.com) 以及其 [资源](https://ping.chinaz.com/fonts.gstatic.com) 都在国内部署，理论上不会存在可访问性的问题，请检查一下本地的网络设置，比如 DNS 设置等或者尝试清空网络浏览器缓存，以及切换到 4G 热点重试一下。

后期可能会将网站所需要的字体等资源选择使用「离线」的方式调用，但是目前还木有更多的计划，谢谢啦。
