### ISSUE TITLE
[PAGE ISSUE]: '官方文档icon404'

### ISSUE THREAD

**Issue by niyuanfa** [cfug/dart.cn#356]
### 页面 URL

https://dart.cn/guides/language/language-tour

### 描述问题

图标展示的英文名，https://dart.cn/assets/translator/css/material-icons.css 报错404

### 期望如何修复

图标正确展示

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/162213037-56cb0756-3d86-4e1a-a943-119b3c5fa033.png)
