### ISSUE TITLE
[PAGE ISSUE]: 'Dart 开发语言概览'

### ISSUE THREAD

**Issue by ubuntu2204** [cfug/dart.cn#382]
### 页面 URL

https://dart.cn/guides/language/language-tour

### 页面源地址

https://github.com/cfug/dart.cn/tree/master/src/_guides/language/language-tour.md

### 描述问题

安卓手机chrome浏览，打不开右上角的”三”

**Comment by chenglu** [comment]
我晚点看看，好像我也没法展开右上角菜单栏。

**Comment by AlexV525** [comment]
调试看了下是 main.js 没有在网页上触发，导致事件没有监听。

**Comment by chenglu** [comment]
@ubuntu2204 问题已经解决，如果有任何问题请随时再开启这个议题向我们提出。
