### ISSUE TITLE
[PAGE ISSUE]: 'Dart 开发语言概览'

### ISSUE THREAD

**Issue by BodhiSun** [cfug/dart.cn#397]
### 页面 URL

https://dart.cn/guides/language/language-tour

### 页面源地址

https://github.com/cfug/dart.cn/tree/master/src/_guides/language/language-tour.md

### 描述问题

![image](https://user-images.githubusercontent.com/11385150/200834567-382db4d5-e703-4ebb-9ba3-6a6f46f0e5fb.png)
划线处的功能讲述是不正确的，final修饰的类变量并不会延迟初始化，而且英文官网里也没有这句话，容易误导只看中文的学习者

### 期望如何修复

删除划线处多余不正确的功能描述

**Comment by chenglu** [comment]
是的，这句话应该被删掉，应该是文档同步的时候上游做了修改但是中文没有及时改动，我马上发一个 PR 来解决这个问题。

**Comment by BodhiSun** [comment]
这个功能没错，类的finale变量(static final 修饰)确实可以实现延迟初始化， 看成实例变量只有finale修饰了。
不过，不知道英文官网为什么 不想描述这一功能点了。

**Comment by AlexV525** [comment]
![image](https://user-images.githubusercontent.com/15884415/201027011-936a452a-4416-42f6-814d-a7f0c7f87c68.png)

**Comment by BodhiSun** [comment]
![image](https://user-images.githubusercontent.com/11385150/201090034-2ac45129-c8ef-4be9-9b73-4511aeaeb1f7.png)
从我的这个case中， '---initA---'是先于"will use aa"打印的，如果加上static修饰 才是"will use aa"先打印

**Comment by AlexV525** [comment]
> 从我的这个case中， '---initA---'是先于"will use aa"打印的，如果加上static修饰 才是"will use aa"先打印

因为没有经过 `static` 修饰的 `aa` 是 `VariableClass` 的成员变量。`final` 修饰的成员变量是在构造时一同初始化的。顶层 `final` 变量和 `static final` 都是延迟初始化的。

移除译文的说明后已经没有误导信息了，如果要修改那么去掉 "类的 final 变量" 也符合条件。
