### ISSUE TITLE
[PAGE ISSUE]: 'Dart 开发语言概览'

### ISSUE THREAD

**Issue by BodhiSun** [cfug/dart.cn#400]
### 页面 URL

https://dart.cn/guides/language/language-tour

### 页面源地址

https://github.com/cfug/dart.cn/tree/master/src/_guides/language/language-tour.md

### 描述问题

![image](https://user-images.githubusercontent.com/11385150/201620997-4540aaba-de38-43b1-b334-0f9723c04659.png)
功能描述不正确，==操作符判断两个对象相等的条件是根据 hashCode方法中某种规则生成的值，并不简单是内容是否一样。
同时英文版描述的也是两个对象是否相等，而不是两个对象的内容是否一样。

### 期望如何修复

修复“== 运算符负责判断两个对象的内容是否一样” 按英文版直译就好

**Comment by chenglu** [comment]
谢谢提出，我开了一个 PR 请看一下修改是否合适。

P.s. 下次可以直接给我们开 PR 哈，期待你的贡献。

**Comment by AlexV525** [comment]
谢谢，由于文档是长久以来多人协作的成果，同时参与校对的人也有更迭，难免有出现过时或词不达意的情况。

**Comment by BodhiSun** [comment]
好👌
