### ISSUE TITLE
[翻译问题] {https://dart.cn/language/variables}

### ISSUE THREAD

**Issue by mobeicanyue** [cfug/dart.cn#442]
### 页面 URL

https://dart.cn/language/variables

### 描述问题

这个页面没有被翻译，我可以认领吗，应该不会太久

### 我想来解决这个问题。

- [x] 我会尝试在 dart.cn 上解决这个问题。

**Comment by AlexV525** [comment]
我看内容不少，估计需要一周。如果确认认领请回复并勾选最后一个选项，谢谢
