### ISSUE TITLE
Get started - 起步：使用 Dart 开发 Web 应用

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dart.cn#61]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/_tutorials/web/get-started.md

文档预览地址：https://dart.cn/tutorials/web/get-started

建议完成天数：5 ~ 7 天

**Comment by AlexV525** [comment]
@evle 是否有继续翻译？

**Comment by evle** [comment]
有, 临近假期比较忙不好意思, 
10.1假期内会翻译完成, 谢谢


在2021年09月21日 22:14，Alex ***@***.***> 写道：

@evle 是否有继续翻译？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
