### ISSUE TITLE
Publishing packages - 发布 package

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dart.cn#80]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/tools/pub/publishing.md

文档预览地址：http://www.dartdoc.cn/tools/pub/publishing

建议完成天数：5 ~ 7 天

**Comment by NeroSong** [comment]
已了解参与流程，申请认领该任务。

预计完成时间：5天

**Comment by chenglu** [comment]
任务领取完成，感谢你的时间！

**Comment by NeroSong** [comment]
期待能贡献自己的力量😊

**Comment by chenglu** [comment]
感谢付出时间，本任务已经完成！
