### ISSUE TITLE
Specification - Dart 编程语言规范 - [润稿]

### ISSUE THREAD

**Issue by cfug-dev** [cfug/dart.cn#93]
Markdown 文档：https://github.com/cfug/dartlang-cn/blob/master/src/_guides/language/spec.md

文档预览地址：http://www.dartdoc.cn/guides/language/spec

建议完成天数：1 ~ 2 天

**Comment by AigeStudio** [comment]
翻译中

**Comment by AlexV525** [comment]
Closing, seems finished in https://github.com/cfug/dart.cn/commit/1430e53313409c1aec2e636bcfecfe69256d635e .
